{% set name = "colour-demosaicing" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colour_demosaicing-{{ version }}.tar.gz
  sha256: b2889c181b413278acb08c5a004a4b1b25525d7dafbe398d4d5558cd0c49aa10

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.11
    - poetry
  run:
    - colour-science >=0.4.0
    - imageio >=2,<3
    - numpy >=1.19,<2
    - python >=3.8,<3.11
    - scipy >=1.5,<2
    - typing-extensions >=4,<5

test:
  imports:
    - colour_demosaicing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.colour-science.org/colour-demosaicing/
  dev_url: https://github.com/colour-science/colour-demosaicing
  doc_url: https://colour-demosaicing.readthedocs.io/en/latest/reference.html
  summary: CFA (Colour Filter Array) Demosaicing Algorithms for Python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AndrewAnnex
